version: "3.7"

services:
  django:
    build: .
    container_name: django
    ports:
      - "8000:8000"
    command: >
      sh -c "/bin/sh start_xvfb.sh
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./app:/app
      - /dev/shm:/dev/shm
    environment:
      - DISPLAY=:10

  celery:
    build: .
    container_name: celery
    command: >
        sh -c "/bin/sh start_xvfb.sh
               celery -A core.celery worker -l INFO -E"
    volumes:
      - ./app:/app
      - /dev/shm:/dev/shm
    depends_on:
      - django
      - redis
    environment:
      - DISPLAY=:10

  celery-beat:
    build: .
    container_name: celery-beat
    command: >
        sh -c "/bin/sh start_xvfb.sh
               celery -A core.celery beat -l INFO"
    volumes:
      - ./app:/app
      - /dev/shm:/dev/shm
    depends_on:
      - django
      - redis
      - celery
    environment:
      - DISPLAY=:10

  redis:
    container_name: redis
    image: "redis:alpine"
    depends_on:
      - django
