# Generated by Django 4.1 on 2022-09-24 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_message_error_alter_message_success'),
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=15)),
                ('text', models.CharField(max_length=250)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.campaign')),
                ('reciver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.bot')),
            ],
        ),
    ]
