# Generated by Django 4.1 on 2022-09-27 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='path',
            field=models.FilePathField(default='', path='driver/sessions'),
        ),
    ]
