# Generated by Django 4.1 on 2022-09-27 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_bot_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bot',
            name='path',
        ),
    ]
