# Generated by Django 4.1 on 2022-09-30 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_bot_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=15)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.bot')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.campaign')),
            ],
        ),
        migrations.CreateModel(
            name='Message_t',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('type', models.IntegerField(choices=[(0, 'Sended'), (1, 'Recived')])),
                ('error', models.CharField(default=None, max_length=100)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.conversation')),
            ],
        ),
    ]
