# Generated by Django 4.1 on 2022-10-01 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_message_t_error'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='campaign',
        ),
        migrations.RemoveField(
            model_name='response',
            name='reciver',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Response',
        ),
    ]
