# Generated by Django 4.1 on 2022-10-01 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_response_campaign_remove_response_reciver_and_more'),
    ]

    operations = [
        migrations.RenameModel('Message_t', 'Message')
    ]
