# Generated by Django 4.1 on 2022-10-01 02:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20221001_0100'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='start',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
